/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odev_4.sozluk;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Aedamantium
 */
public class KelimeEkle extends javax.swing.JFrame {
    int a = 0;
    SozlukAP s = new SozlukAP();
    static KelimeEkle k = new KelimeEkle();

    /**
     * Creates new form KelimeEkle
     */
    public KelimeEkle() {
        initComponents();
        if (jLabel1.getText().equals("Türkçe")) {
            jLabel3.setText("ingilizce karşılığı");
        }
        else if (jLabel1.getText().equals("İngilizce")) {
            jLabel3.setText("türkçe karşılığı");
        }
        Sozluk.kontrol = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        degistir1 = new javax.swing.JButton();
        kelime = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        karsiligi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelime Ekle");

        jLabel2.setText("Türkçe");

        degistir1.setText("-->");
        degistir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelimeEkleAP(evt);
            }
        });

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelimeEkleAP(evt);
            }
        });

        jLabel1.setText("İngilizce");

        jLabel3.setText("ingilizce karşılığı");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(degistir1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(kelime)
                    .addComponent(karsiligi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degistir1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addComponent(kelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karsiligi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ekle)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KelimeEkleAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelimeEkleAP
        // TODO add your handling code here:
        
        JButton kb = (JButton)evt.getSource();
        if (kb.equals(degistir1)) {
            if (jLabel1.getText().equals("İngilizce")) {
                jLabel1.setText("Türkçe");
            }
            else if (jLabel1.getText().equals("Türkçe")) {
                jLabel1.setText("İngilizce");
            }
            if (jLabel2.getText().equals("İngilizce")) {
                jLabel2.setText("Türkçe");
            }
            else if (jLabel2.getText().equals("Türkçe")) {
                jLabel2.setText("İngilizce");
            }
            if (jLabel1.getText().equals("Türkçe")) {
                jLabel3.setText("ingilizce karşılığı");
            }
            else if (jLabel1.getText().equals("İngilizce")) {
                jLabel3.setText("türkçe karşılığı");
            }
        }
        else if (kb.equals(ekle) && (!kelime.getText().equals("") && !karsiligi.getText().equals(""))) { 
            if (jLabel1.getText().equals("Türkçe")) {
              String yeni = "";
              yeni = yeni.concat(kelime.getText()).concat("/").concat(karsiligi.getText());
              T_ekle(yeni);
              Sozluk.jLabel8.setText("EKLENDİ");
            }
            else if (jLabel1.getText().equals("İngilizce")) {
              String yeni = "" ; 
              yeni = yeni.concat(kelime.getText()).concat("/").concat(karsiligi.getText());
              E_ekle(yeni);
              Sozluk.jLabel8.setText("EKLENDİ"); 
            }
            kelime.setText("");
            karsiligi.setText("");
            Sozluk.kontrol = 0;
            this.dispose();
        }
        
    }//GEN-LAST:event_KelimeEkleAP

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelimeEkle().setVisible(true);
            }
        });
    }
    
    static void T_ekle(String kelime){
        try {
            BufferedWriter t_ekle = new BufferedWriter(new FileWriter("tureng.txt",true));      
                t_ekle.newLine();
                t_ekle.write(kelime);
                t_ekle.close();
                Sozluk.tur_eng.add(kelime);
        } catch (IOException ex) {
            Logger.getLogger(KelimeEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    static void E_ekle(String kelime){        
        try {
            BufferedWriter e_ekle = new BufferedWriter(new FileWriter("engtur.txt",true));
                e_ekle.newLine();
                e_ekle.write(kelime);
                e_ekle.close(); 
                Sozluk.eng_tur.add(kelime);
        } catch (IOException ex) {
            Logger.getLogger(KelimeEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    static void kelimeEkleAc(String a , String b ,String c){            
            KelimeEkle.jLabel1.setText(a);
            KelimeEkle.jLabel2.setText(b);
            KelimeEkle.jLabel3.setText(b+" karşılığı");    
        k.setVisible(true);
        KelimeEkle.kelime.setText(c);
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degistir1;
    private javax.swing.JButton ekle;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JTextField karsiligi;
    public static javax.swing.JTextField kelime;
    // End of variables declaration//GEN-END:variables
}
