/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odev_4.sozluk;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

/**
 *
 * @author Aedamantium
 */
public class Sozluk extends javax.swing.JFrame {
    
    static ArrayList<String> eng_tur = new ArrayList<>();
    static ArrayList<String> tur_eng = new ArrayList<>();
    
    SozlukAP s = new SozlukAP();
    DefaultListModel d = new DefaultListModel();
    static int kontrol = 0;
 
    /**
     * Creates new form Sozluk
     */
    public Sozluk() {        
        initComponents();       
        //Tureng icin
        s.TlisteyeAt(tur_eng);
        //Engtur icin
        s.ElisteyeAt(eng_tur);
        jDialog1.setLocation(this.getLocation());
        jDialog2.setLocation(this.getLocation());        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cevap = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        degistir = new javax.swing.JButton();
        kelimeGiris = new javax.swing.JTextField();
        cevir = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ekle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(45, 45, 250, 150));
        jDialog1.setLocationByPlatform(true);

        jLabel3.setText("LÜTFEN GEÇERLİ BİR KELİME GİRİNİZ!");

        jButton1.setText("Tamam(OK)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("(Please enter a valid word!)");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jDialog2.setBounds(new java.awt.Rectangle(50, 50, 350, 150));

        jLabel7.setText("Girdiğiniz kelime ile tam bir eşleşme bulunamadı.");

        jButton2.setText("Eklemek için tıklayın");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("İptal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SÖZLÜK");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(cevap);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 146, -1, -1));

        jLabel1.setText("İngilizce");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 35, -1, -1));

        jLabel2.setText("Türkçe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 35, 48, -1));

        degistir.setText("-->");
        degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SozlukAP(evt);
            }
        });
        getContentPane().add(degistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 31, 63, -1));

        kelimeGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kelimeGiris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kelimeGirisKeyPressed(evt);
            }
        });
        getContentPane().add(kelimeGiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 71, 208, -1));

        cevir.setText("Çevir");
        cevir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SozlukAP(evt);
            }
        });
        getContentPane().add(cevir, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, 208, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Aradığınız kelime");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Sözlükte bulunamadı.");

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ekle)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ekle)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ekle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 146, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 261, 22));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SozlukAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SozlukAP
        // TODO add your handling code here:
        JButton sb = (JButton)evt.getSource();
        d.clear();
        jLabel8.setText("");
        if (sb.equals(degistir)) {
            if (jLabel1.getText().equals("İngilizce")) {
                jLabel1.setText("Türkçe");
            }
            else if (jLabel1.getText().equals("Türkçe")) {
                jLabel1.setText("İngilizce");
            }
            if (jLabel2.getText().equals("İngilizce")) {
                jLabel2.setText("Türkçe");
            }
            else if (jLabel2.getText().equals("Türkçe")) {
                jLabel2.setText("İngilizce");
            }  
            jLayeredPane1.setVisible(true);
            jLayeredPane2.setVisible(false);
        }        
        else if (sb.equals(cevir) && !kelimeGiris.getText().equals("")) { 
            if (jLabel1.getText().equals("Türkçe") ) {
                for (int i = 0; i < turkcedenIngilizceye(kelimeGiris.getText()).size(); i++) {
                    d.addElement(turkcedenIngilizceye(kelimeGiris.getText()).get(i));
                }
                cevap.setModel(d);
                if (exactWordT(kelimeGiris.getText()) == false && !d.isEmpty()) {
                  jDialog2.setVisible(true);
                }
            }
            else if(jLabel1.getText().equals("İngilizce") ){
                for (int i = 0; i < ingilizcedenTurkceye(kelimeGiris.getText()).size(); i++) {
                    d.addElement(ingilizcedenTurkceye(kelimeGiris.getText()).get(i));
                }
                cevap.setModel(d);
                if (exactWordE(kelimeGiris.getText()) == false && !d.isEmpty()) {
                  jDialog2.setVisible(true);
                }
            }
            if (d.isEmpty() && kontrol == 0) {
                jLayeredPane1.setVisible(false);
                jLayeredPane2.setVisible(true);
                kontrol++;
            }
            else if(!d.isEmpty()){
                jLayeredPane1.setVisible(true);
                jLayeredPane2.setVisible(false);
            }
             if (jLabel1.getText().equals("Türkçe") && (s.gecerliMiT(kelimeGiris.getText()) == false)) {
                jDialog1.setVisible(true);
                kontrol++;
            }
            else if (jLabel1.getText().equals("İngilizce") && (s.gecerliMiE(kelimeGiris.getText()) == false)) {
                jDialog1.setVisible(true);
                kontrol++;
            }        
        }
    }//GEN-LAST:event_SozlukAP

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kelimeGiris.setText("");
        jDialog1.setVisible(false);
        kontrol = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        // TODO add your handling code here:
        KelimeEkle.kelimeEkleAc(jLabel1.getText(),jLabel2.getText() ,kelimeGiris.getText());
    }//GEN-LAST:event_ekleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        jDialog2.setVisible(false);
        KelimeEkle.kelimeEkleAc(jLabel1.getText(),jLabel2.getText(),kelimeGiris.getText());        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kelimeGirisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelimeGirisKeyPressed
        // TODO add your handling code here:
         if ( !kelimeGiris.getText().equals("") && evt.getKeyCode() == KeyEvent.VK_ENTER ) { 
            d.clear();
            if (jLabel1.getText().equals("Türkçe") && (s.gecerliMiT(kelimeGiris.getText()) == false)) {
                jDialog1.setVisible(true);
                kontrol++;
            }
            else if (jLabel1.getText().equals("İngilizce") && (s.gecerliMiE(kelimeGiris.getText()) == false)) {
                jDialog1.setVisible(true);
                kontrol++;
            }
            
            if (jLabel1.getText().equals("Türkçe") ) {
                for (int i = 0; i < turkcedenIngilizceye(kelimeGiris.getText()).size(); i++) {
                    d.addElement(turkcedenIngilizceye(kelimeGiris.getText()).get(i));
                }
                cevap.setModel(d);
                if (exactWordT(kelimeGiris.getText()) == false && !d.isEmpty()) {
                  jDialog2.setVisible(true);
                }
            }
            else if(jLabel1.getText().equals("İngilizce") ){
                for (int i = 0; i < ingilizcedenTurkceye(kelimeGiris.getText()).size(); i++) {
                    d.addElement(ingilizcedenTurkceye(kelimeGiris.getText()).get(i));
                }
                cevap.setModel(d);
                if (exactWordE(kelimeGiris.getText()) == false && !d.isEmpty()) {
                  jDialog2.setVisible(true);
                }
            }
            if (d.isEmpty() && kontrol == 0) {
                jLayeredPane1.setVisible(false);
                jLayeredPane2.setVisible(true);
            }
            else{
                jLayeredPane1.setVisible(true);
                jLayeredPane2.setVisible(false);
            }
        }
    }//GEN-LAST:event_kelimeGirisKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sozluk().setVisible(true);
            }
        });
    }
    
    static ArrayList turkcedenIngilizceye(String kelime/*text field a girilen kelime*/){        
        ArrayList<String> dizi = new ArrayList<>();
        for (int i = 0; i < tur_eng.size(); i++) {
          String t = tur_eng.get(i).substring(0, tur_eng.get(i).indexOf("/"));          
          Pattern p = Pattern.compile("\\b"+kelime+"\\b");
          Matcher m = p.matcher(t);
            if (m.find()) {
                dizi.add(t.concat(": ").concat(tur_eng.get(i).substring(tur_eng.get(i).indexOf("/")+1, tur_eng.get(i).length())));                
            }
        }
       return dizi;  
    }
    static ArrayList ingilizcedenTurkceye(String kelime/*text field a girilen kelime*/){
        ArrayList<String> dizi = new ArrayList<>();
        for (int i = 0; i < eng_tur.size(); i++) {
          String t = eng_tur.get(i).substring(0, eng_tur.get(i).indexOf("/"));
          Pattern p = Pattern.compile("\\b"+kelime+"\\b");
          Matcher m = p.matcher(t);
            if (m.find()) {
                dizi.add(t.concat(": ").concat(eng_tur.get(i).substring(eng_tur.get(i).indexOf("/")+1, eng_tur.get(i).length())));                
            }
        }
       return dizi;  
    }
    static boolean exactWordT(String kelime){
        boolean b = false;
        for (int i = 0; i < tur_eng.size(); i++) {
          String t = tur_eng.get(i).substring(0, tur_eng.get(i).indexOf("/"));
          Pattern p = Pattern.compile(kelime);
          Matcher m = p.matcher(t);
            if (m.matches()) {
                b = true;               
            }
        }
       return b;  
    }
    static boolean exactWordE(String kelime){
        boolean b = false;
        for (int i = 0; i < eng_tur.size(); i++) {
          String t = eng_tur.get(i).substring(0, eng_tur.get(i).indexOf("/"));
          Pattern p = Pattern.compile(kelime);
          Matcher m = p.matcher(t);
            if (m.matches()) {
                b = true;               
            }
        }
       return b;  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList cevap;
    private javax.swing.JButton cevir;
    private javax.swing.JButton degistir;
    private javax.swing.JButton ekle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField kelimeGiris;
    // End of variables declaration//GEN-END:variables
}
